// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9EI7TjtbXrH9xZsl0V5tuW69iz1cr_7g',
    appId: '1:353604172058:android:9de6908864555b0f2914a3',
    messagingSenderId: '353604172058',
    projectId: 'fixilyaappbackend',
    storageBucket: 'fixilyaappbackend.firebasestorage.app',
  );

  // TODO: Replace placeholder values with real iOS config from FlutterFire CLI
  // Run: flutterfire configure --platforms=ios
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9EI7TjtbXrH9xZsl0V5tuW69iz1cr_7g',
    appId: '1:353604172058:ios:PLACEHOLDER',
    messagingSenderId: '353604172058',
    projectId: 'fixilyaappbackend',
    storageBucket: 'fixilyaappbackend.firebasestorage.app',
    iosBundleId: 'com.fixilya.app',
  );
}
