import 'package:font_awesome_flutter/font_awesome_flutter.dart';

class GlobalVariables {
  static const List<Map<String, dynamic>> availableSkills = [
    {'name': 'All Services', 'icon': FontAwesomeIcons.briefcase},
    {'name': 'Plumbing', 'icon': FontAwesomeIcons.faucet},
    {'name': 'Electricity', 'icon': FontAwesomeIcons.bolt},
    {'name': 'Carpentry', 'icon': FontAwesomeIcons.hammer},
    {'name': 'Painting', 'icon': FontAwesomeIcons.paintRoller},
    {'name': 'Concrete', 'icon': FontAwesomeIcons.cubesStacked},
    {'name': 'Facade coverings', 'icon': FontAwesomeIcons.building},
    {'name': 'Cleaning', 'icon': FontAwesomeIcons.broom},
    {'name': 'Gardening', 'icon': FontAwesomeIcons.seedling},
    {'name': 'Welding', 'icon': FontAwesomeIcons.wrench},
    {'name': 'Aluminum', 'icon': FontAwesomeIcons.cubes},
    {'name': 'Masonry', 'icon': FontAwesomeIcons.home},
    {'name': 'Zellige', 'icon': FontAwesomeIcons.thLarge},
    {'name': 'AC Repair', 'icon': FontAwesomeIcons.snowflake},
    {'name': 'Appliance Repair', 'icon': FontAwesomeIcons.plug},
    {'name': 'Smart Home Setup', 'icon': FontAwesomeIcons.house},
  ];

  /// Test/placeholder handyman data for UI development and testing.
  /// All personal data below is obviously fake and must not be used in production.
  static const List<Map<String, dynamic>> fakeHandymen = [
    {
      'uid': 'test_handyman_01',
      'fullName': 'Test Handyman 1',
      'skills': ['Cleaning'],
      'city': 'Casablanca',
      'rating': 4.2,
      'reviews': 10,
      'category': 'Cleaning',
      'phone': '+212000000001',
      'hourlyRate': 150,
      'profilePicture': '',
      'approved': true,
      'experience': '8 years',
      'completedJobs': 45,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio': 'Test handyman profile for development purposes. This is placeholder data.',
    },
    {
      'uid': 'test_handyman_02',
      'fullName': 'Test Handyman 2',
      'skills': ['Electricity'],
      'city': 'Rabat',
      'rating': 4.9,
      'reviews': 5,
      'category': 'Electricity',
      'phone': '+212000000002',
      'hourlyRate': 180,
      'profilePicture': '',
      'approved': true,
      'experience': '6 years',
      'completedJobs': 12,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio': 'Test handyman profile for development purposes. This is placeholder data.',
    },
    {
      'uid': 'test_handyman_03',
      'fullName': 'Test Handyman 3',
      'skills': ['Electricity'],
      'city': 'Nador',
      'rating': 4.7,
      'reviews': 156,
      'category': 'Electricity',
      'phone': '+212000000003',
      'hourlyRate': 140,
      'profilePicture': '',
      'approved': true,
      'experience': '6 years',
      'completedJobs': 198,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio': 'Test handyman profile for development purposes. This is placeholder data.',
    },
    {
      'uid': 'test_handyman_04',
      'fullName': 'Test Handyman 4',
      'skills': ['Electricity'],
      'city': 'Fes',
      'rating': 4.6,
      'reviews': 93,
      'category': 'Electricity',
      'phone': '+212000000004',
      'hourlyRate': 120,
      'profilePicture': '',
      'approved': true,
      'experience': '5 years',
      'completedJobs': 167,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio': 'Test handyman profile for development purposes. This is placeholder data.',
    },
    {
      'uid': 'test_handyman_05',
      'fullName': 'Test Handyman 5',
      'skills': ['Appliance Repair'],
      'city': 'Marrakech',
      'rating': 4.9,
      'reviews': 201,
      'category': 'Appliance Repair',
      'phone': '+212000000005',
      'hourlyRate': 200,
      'profilePicture': '',
      'approved': true,
      'experience': '10 years',
      'completedJobs': 421,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio': 'Test handyman profile for development purposes. This is placeholder data.',
    },
    {
      'uid': 'test_handyman_06',
      'fullName': 'Test Handyman 6',
      'skills': ['Facade coverings'],
      'city': 'Tangier',
      'rating': 4.5,
      'reviews': 74,
      'category': 'Facade Coverings',
      'phone': '+212000000006',
      'hourlyRate': 110,
      'profilePicture': '',
      'approved': true,
      'experience': '4 years',
      'completedJobs': 134,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio': 'Test handyman profile for development purposes. This is placeholder data.',
    },
    {
      'uid': 'test_handyman_07',
      'fullName': 'Test Handyman 7',
      'skills': ['Painting'],
      'city': 'Agadir',
      'rating': 4.5,
      'reviews': 74,
      'category': 'Painting',
      'phone': '+212000000007',
      'hourlyRate': 110,
      'profilePicture': '',
      'approved': true,
      'experience': '4 years',
      'completedJobs': 134,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio': 'Test handyman profile for development purposes. This is placeholder data.',
    },
    {
      'uid': 'test_handyman_08',
      'fullName': 'Test Handyman 8',
      'skills': ['Painting'],
      'city': 'Casablanca',
      'rating': 4.5,
      'reviews': 74,
      'category': 'Painting',
      'phone': '+212000000008',
      'hourlyRate': 110,
      'profilePicture': '',
      'approved': true,
      'experience': '4 years',
      'completedJobs': 134,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio': 'Test handyman profile for development purposes. This is placeholder data.',
    },
    {
      'uid': 'test_handyman_09',
      'fullName': 'Test Handyman 9',
      'skills': ['Welding'],
      'city': 'Rabat',
      'rating': 4.5,
      'reviews': 74,
      'category': 'Welding',
      'phone': '+212000000009',
      'hourlyRate': 110,
      'profilePicture': '',
      'approved': true,
      'experience': '4 years',
      'completedJobs': 134,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio': 'Test handyman profile for development purposes. This is placeholder data.',
    },
    {
      'uid': 'test_handyman_10',
      'fullName': 'Test Handyman 10',
      'skills': ['Concrete'],
      'city': 'Nador',
      'rating': 4.5,
      'reviews': 74,
      'category': 'Concrete',
      'phone': '+212000000010',
      'hourlyRate': 110,
      'profilePicture': '',
      'approved': true,
      'experience': '4 years',
      'completedJobs': 134,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio': 'Test handyman profile for development purposes. This is placeholder data.',
    },
    {
      'uid': 'test_handyman_11',
      'fullName': 'Test Handyman 11',
      'skills': ['Aluminum'],
      'city': 'Fes',
      'rating': 4.5,
      'reviews': 74,
      'category': 'Aluminum',
      'phone': '+212000000011',
      'hourlyRate': 110,
      'profilePicture': '',
      'approved': true,
      'experience': '4 years',
      'completedJobs': 134,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio': 'Test handyman profile for development purposes. This is placeholder data.',
    },
    {
      'uid': 'test_handyman_12',
      'fullName': 'Test Handyman 12',
      'skills': ['Zellige', 'Masonry'],
      'city': 'Marrakech',
      'rating': 4.5,
      'reviews': 74,
      'category': 'Zellige',
      'phone': '+212000000012',
      'hourlyRate': 110,
      'profilePicture': '',
      'approved': true,
      'experience': '4 years',
      'completedJobs': 134,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio': 'Test handyman profile for development purposes. This is placeholder data.',
    },
    {
      'uid': 'test_handyman_13',
      'fullName': 'Test Handyman 13',
      'skills': ['Zellige', 'Masonry'],
      'city': 'Tangier',
      'rating': 4.5,
      'reviews': 74,
      'category': 'Zellige',
      'phone': '+212000000013',
      'hourlyRate': 110,
      'profilePicture': '',
      'approved': true,
      'experience': '4 years',
      'completedJobs': 134,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio': 'Test handyman profile for development purposes. This is placeholder data.',
    },
    {
      'uid': 'test_handyman_14',
      'fullName': 'Test Handyman 14',
      'skills': ['Plumbing'],
      'city': 'Agadir',
      'rating': 4.5,
      'reviews': 74,
      'category': 'Plumbing',
      'phone': '+212000000014',
      'hourlyRate': 110,
      'profilePicture': '',
      'approved': true,
      'experience': '4 years',
      'completedJobs': 134,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio': 'Test handyman profile for development purposes. This is placeholder data.',
    },
    {
      'uid': 'test_handyman_15',
      'fullName': 'Test Handyman 15',
      'skills': ['Carpentry'],
      'city': 'Casablanca',
      'rating': 4.5,
      'reviews': 74,
      'category': 'Carpentry',
      'phone': '+212000000015',
      'hourlyRate': 110,
      'profilePicture': '',
      'approved': true,
      'experience': '4 years',
      'completedJobs': 134,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio': 'Test handyman profile for development purposes. This is placeholder data.',
    },
  ];

  static const List<String> cities = [
    'All Cities',
    'Nador',
    'Casablanca',
    'Rabat',
    'Fes',
    'Marrakech',
    'Tangier',
    'Agadir',
  ];

  static String selectedCity = 'All Cities';
  static String selectedCategory = 'All Services';
}
