import 'package:font_awesome_flutter/font_awesome_flutter.dart';

class GlobalVariables {
  static const List<Map<String, dynamic>> availableSkills = [
    {'name': 'All Services', 'icon': FontAwesomeIcons.briefcase},
    {'name': 'Plumbing', 'icon': FontAwesomeIcons.faucet},
    {'name': 'Electricity', 'icon': FontAwesomeIcons.bolt},
    {'name': 'Carpentry', 'icon': FontAwesomeIcons.hammer},
    {'name': 'Painting', 'icon': FontAwesomeIcons.paintRoller},
    {'name': 'Concrete', 'icon': FontAwesomeIcons.cubesStacked},
    {'name': 'Facade coverings', 'icon': FontAwesomeIcons.building},
    {'name': 'Cleaning', 'icon': FontAwesomeIcons.broom},
    {'name': 'Gardening', 'icon': FontAwesomeIcons.seedling},
    {'name': 'Welding', 'icon': FontAwesomeIcons.wrench},
    {'name': 'Aluminum', 'icon': FontAwesomeIcons.cubes},
    {'name': 'Masonry', 'icon': FontAwesomeIcons.home},
    {'name': 'Zellige', 'icon': FontAwesomeIcons.thLarge},
    {'name': 'AC Repair', 'icon': FontAwesomeIcons.snowflake},
    {'name': 'Appliance Repair', 'icon': FontAwesomeIcons.plug},
    // {'name': 'Electrical Wiring', 'icon': FontAwesomeIcons.bolt},
    // {'name': 'Panel Installation', 'icon': FontAwesomeIcons.plug},
    {'name': 'Smart Home Setup', 'icon': FontAwesomeIcons.house},
  ];

  static const List<Map<String, dynamic>> fakeHandymen = [
    {
      'id': 'fake_1', // ✅ Add unique ID
      'name': 'Siham',
      'skills': ['Cleaning'], // ✅ Changed to match Firebase structure
      'city': 'Nador',
      'rating': 0,
      'reviews': 0,
      'category': 'Cleaning', // ✅ Add 'category' for easier filtering
      'phone': '+212682483044',
      'hourlyRate': 150,
      'profilePicture': '',
      'approved': true, // ✅ Changed 'verified' to 'approved'
      'experience': '8 years',
      'completedJobs': 0,
      'isAvailable': true,
      'verified': true, // ✅ Add availability
      'workImages': [],
      'bio':
          'Experienced cleaner with 8 years of expertise in residential and commercial cleaning. Committed to delivering top-notch service and customer satisfaction. Available for regular cleaning, deep cleaning, and move-in/move-out cleaning services.',
    },
    {
      'id': 'fake_2',
      'name': 'Khaled EL OMRANI',
      'skills': ['Electricity'],
      'city': 'Nador',
      'rating': 4.9,
      'reviews': 5,
      'category': 'Electricity', // ✅ Add 'category' for easier filtering
      'phone': '+212777991513',
      'hourlyRate': 180,
      'profilePicture': '',
      'approved': true,
      'experience': '6 years',
      'completedJobs': 12,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio':
          'Experienced cleaner with 8 years of expertise in residential and commercial cleaning. Committed to delivering top-notch service and customer satisfaction. Available for regular cleaning, deep cleaning, and move-in/move-out cleaning services.',
    },
    {
      'id': 'fake_3',
      'name': 'Kamal',
      'skills': ['Electricity'],
      'city': 'Nador',
      'rating': 4.7,
      'reviews': 156,
      'category': 'Electricity', // ✅ Add 'category' for easier filtering
      'phone': '+212601918727',
      'hourlyRate': 140,
      'profilePicture': '',
      'approved': true,
      'experience': '6 years',
      'completedJobs': 198,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio':
          'Experienced cleaner with 8 years of expertise in residential and commercial cleaning. Committed to delivering top-notch service and customer satisfaction. Available for regular cleaning, deep cleaning, and move-in/move-out cleaning services.',
    },
    {
      'id': 'fake_4',
      'name': 'Mohamed ASSILA',
      'skills': ['Electricity'],
      'city': 'Nador',
      'rating': 4.6,
      'reviews': 93,
      'category': 'Electricity', // ✅ Add 'category' for easier filtering
      'phone': '+212606826196',
      'hourlyRate': 120,
      'profilePicture': '',
      'approved': true,
      'experience': '5 years',
      'completedJobs': 167,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio':
          'Experienced cleaner with 8 years of expertise in residential and commercial cleaning. Committed to delivering top-notch service and customer satisfaction. Available for regular cleaning, deep cleaning, and move-in/move-out cleaning services.',
    },
    {
      'id': 'fake_5',
      'name': 'Waeil WARIACHI',
      'skills': ['Appliance Repair'],
      'city': 'Nador',
      'rating': 4.9,
      'reviews': 201,
      'category': 'Appliance Repair', // ✅ Add 'category' for easier filtering
      'phone': '+212623417072',
      'hourlyRate': 200,
      'profilePicture': '',
      'approved': true,
      'experience': '10 years',
      'completedJobs': 421,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio':
          'Experienced cleaner with 8 years of expertise in residential and commercial cleaning. Committed to delivering top-notch service and customer satisfaction. Available for regular cleaning, deep cleaning, and move-in/move-out cleaning services.',
    },
    {
      'id': 'fake_6',
      'name': 'Mohamed IKKEN',
      'skills': ['Facade coverings'],
      'city': 'Nador',
      'rating': 4.5,
      'reviews': 74,
      'category': 'Facade Coverings', // ✅ Add 'category' for easier filtering
      'phone': '+212695581770',
      'hourlyRate': 110,
      'profilePicture': '',
      'approved': true,
      'experience': '4 years',
      'completedJobs': 134,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio':
          'Experienced cleaner with 8 years of expertise in residential and commercial cleaning. Committed to delivering top-notch service and customer satisfaction. Available for regular cleaning, deep cleaning, and move-in/move-out cleaning services.',
    },
    {
      'id': 'fake_7',
      'name': 'Soufian KOLIGHA',
      'skills': ['Painting'],
      'city': 'Nador',
      'rating': 4.5,
      'reviews': 74,
      'category': 'Painting', // ✅ Add 'category' for easier filtering
      'phone': '+212644659405',
      'hourlyRate': 110,
      'profilePicture': '',
      'approved': true,
      'experience': '4 years',
      'completedJobs': 134,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio':
          'Experienced cleaner with 8 years of expertise in residential and commercial cleaning. Committed to delivering top-notch service and customer satisfaction. Available for regular cleaning, deep cleaning, and move-in/move-out cleaning services.',
    },
    {
      'id': 'fake_8',
      'name': 'Abdelhak KOLIGHA',
      'skills': ['Painting'],
      'city': 'Nador',
      'rating': 4.5,
      'reviews': 74,
      'category': 'Painting', // ✅ Add 'category' for easier filtering
      'phone': '+212642691733',
      'hourlyRate': 110,
      'profilePicture': '',
      'approved': true,
      'experience': '4 years',
      'completedJobs': 134,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio':
          'Experienced cleaner with 8 years of expertise in residential and commercial cleaning. Committed to delivering top-notch service and customer satisfaction. Available for regular cleaning, deep cleaning, and move-in/move-out cleaning services.',
    },
    {
      'id': 'fake_9',
      'name': 'Abdelwahed',
      'skills': ['Welding'],
      'city': 'Nador',
      'rating': 4.5,
      'reviews': 74,
      'category': 'Welding', // ✅ Add 'category' for easier filtering
      'phone': '+212757438410',
      'hourlyRate': 110,
      'profilePicture': '',
      'approved': true,
      'experience': '4 years',
      'completedJobs': 134,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio':
          'Experienced cleaner with 8 years of expertise in residential and commercial cleaning. Committed to delivering top-notch service and customer satisfaction. Available for regular cleaning, deep cleaning, and move-in/move-out cleaning services.',
    },
    {
      'id': 'fake_10',
      'name': 'Youssef',
      'skills': ['Concrete'],
      'city': 'Nador',
      'rating': 4.5,
      'reviews': 74,
      'category': 'Concrete', // ✅ Add 'category' for easier filtering
      'phone': '+212605153771',
      'hourlyRate': 110,
      'profilePicture': '',
      'approved': true,
      'experience': '4 years',
      'completedJobs': 134,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio':
          'Experienced cleaner with 8 years of expertise in residential and commercial cleaning. Committed to delivering top-notch service and customer satisfaction. Available for regular cleaning, deep cleaning, and move-in/move-out cleaning services.',
    },
    {
      'id': 'fake_11',
      'name': 'Kroom',
      'skills': ['Aluminum'],
      'city': 'Nador',
      'rating': 4.5,
      'reviews': 74,
      'category': 'Aluminum', // ✅ Add 'category' for easier filtering
      'phone': '+212694645584',
      'hourlyRate': 110,
      'profilePicture': '',
      'approved': true,
      'experience': '4 years',
      'completedJobs': 134,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio':
          'Experienced cleaner with 8 years of expertise in residential and commercial cleaning. Committed to delivering top-notch service and customer satisfaction. Available for regular cleaning, deep cleaning, and move-in/move-out cleaning services.',
    },
    {
      'id': 'fake_12',
      'name': 'Zouhir',
      'skills': ['Zellige', 'Masonry'],
      'city': 'Nador',
      'rating': 4.5,
      'reviews': 74,
      'category': 'Zellige', // ✅ Add 'category' for easier filtering
      'phone': '+212699449970',
      'hourlyRate': 110,
      'profilePicture': '',
      'approved': true,
      'experience': '4 years',
      'completedJobs': 134,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio':
          'Experienced cleaner with 8 years of expertise in residential and commercial cleaning. Committed to delivering top-notch service and customer satisfaction. Available for regular cleaning, deep cleaning, and move-in/move-out cleaning services.',
    },
    {
      'id': 'fake_13',
      'name': 'Youssef',
      'skills': ['Zellige', 'Masonry'],
      'city': 'Nador',
      'rating': 4.5,
      'reviews': 74,
      'category': 'Zellige', // ✅ Add 'category' for easier filtering
      'phone': '+212699449970',
      'hourlyRate': 110,
      'profilePicture': '',
      'approved': true,
      'experience': '4 years',
      'completedJobs': 134,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio':
          'Experienced cleaner with 8 years of expertise in residential and commercial cleaning. Committed to delivering top-notch service and customer satisfaction. Available for regular cleaning, deep cleaning, and move-in/move-out cleaning services.',
    },
    {
      'id': 'fake_14',
      'name': 'Soufian',
      'skills': ['Plumbing'],
      'city': 'Nador',
      'rating': 4.5,
      'reviews': 74,
      'category': 'Plumbing', // ✅ Add 'category' for easier filtering
      'phone': '+212658603906',
      'hourlyRate': 110,
      'profilePicture': '',
      'approved': true,
      'experience': '4 years',
      'completedJobs': 134,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio':
          'Experienced cleaner with 8 years of expertise in residential and commercial cleaning. Committed to delivering top-notch service and customer satisfaction. Available for regular cleaning, deep cleaning, and move-in/move-out cleaning services.',
    },
    {
      'id': 'fake_15',
      'name': 'Mosa',
      'skills': ['Carpentry'],
      'city': 'Nador',
      'rating': 4.5,
      'reviews': 74,
      'category': 'Carpentry', // ✅ Add category for easier filtering
      'phone': '+212634882102',
      'hourlyRate': 110,
      'profilePicture': '',
      'approved': true,
      'experience': '4 years',
      'completedJobs': 134,
      'isAvailable': true,
      'verified': true,
      'workImages': [],
      'bio':
          'Experienced cleaner with 8 years of expertise in residential and commercial cleaning. Committed to delivering top-notch service and customer satisfaction. Available for regular cleaning, deep cleaning, and move-in/move-out cleaning services.',
    },
  ];

  static const List<String> cities = [
    'All Cities',
    'Nador',
    'Casablanca',
    'Rabat',
    'Fes',
    'Marrakech',
    'Tangier',
    'Agadir',
  ];

  static String selectedCity = 'All Cities';
  static String selectedCategory = 'All Services';
}
